PortfolioWebSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>', views.project_detail, name='project_detail')
]

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=100)
    image = models.CharField(max_length=100)
    url = models.URLField()

projects/views.py
from django.shortcuts import render
from projects.models import Project

# Create your views here.
def all_projects(request):
    # query the db to return all project objects
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html', {'projects': projects})

def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects/detail.html', {'project': project})

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h1>All projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2" style="width:170px">
                <img class="card-img-top" src="{% static project.image %}">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href=" {% url 'projects:project_detail' project.pk %} " class="btn btn-primary">Read More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}
    <h1> {{ project.title }} </h1>
        <div class="row">
            <div class="col-md-8">
                <img src="{% static project.image %}" alt=" {{ project.description }}">
            </div>
            <div class="col-md-4">
                <h5>About the project</h5>
                <p> {{ project.description }} </p>
                <h5>Build with:</h5>
                <p> {{ project.technology}} </p>
                <h5>Link to project on github:</h5>
                <a href="url"> {{ project.url }} </a>
            </div>
        </div>
{% endblock %}